# Generated by Django 3.0.6 on 2020-05-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_pics',
            field=models.ImageField(default='image missing', upload_to='imagess/'),
        ),
    ]
