# Generated by Django 3.0.6 on 2020-05-22 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20200522_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_Descrption',
            new_name='image_descrption',
        ),
    ]
