# Generated by Django 3.0.6 on 2020-05-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20200523_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_pics',
            field=models.ImageField(default='image missing', upload_to='images/'),
        ),
    ]
