# Generated by Django 3.0.6 on 2020-05-24 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_auto_20200523_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_pics',
            field=models.ImageField(upload_to='images/%Y/%n/%d'),
        ),
        migrations.AlterField(
            model_name='image',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='photos.Location'),
        ),
    ]
