# Generated by Django 3.0.6 on 2020-05-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_auto_20200522_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_pics',
            field=models.ImageField(default='image missing', upload_to='images'),
        ),
    ]
