# Generated by Django 3.0.6 on 2020-05-25 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_auto_20200524_1054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['pub_date']},
        ),
    ]
