# Generated by Django 3.0.6 on 2020-05-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_auto_20200525_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_pics',
            field=models.ImageField(upload_to=''),
        ),
    ]
